# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#on:
#  push:
#    branches:
#      - development
#      - production
#      - testpipeline
#  pull_request:
#    branches:
#      - testpipeline
#      - production


jobs:
  check-format:
    name: Check format
    runs-on: ubuntu-latest
    container: crystallang/crystal
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check sources format
        run: crystal tool format --check

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    container: crystallang/crystal
    steps:
      - name: Checkout
        uses: actions/checkout@v1      
      - name: Shards installing
        run:  shards install 
      - name: Crystal spec running
        run:  crystal spec 
      - name: Ameba
        run:  crystal bin/ameba.cr
